testsFile=tests.yaml
testDataFile=testData.yaml
env=qa
parallel=true
threads=5
suiteName=AutomationSuite
appUrl=https://rahulshettyacademy.com/loginpagePractise/
overrideReport=true
runTests=
#runTests=TC001 - to run specific test
#runTests=TC001,TC002 - Run multiple tests
runTags=smoke,sanity
#runTags=smoke - run smoke
#runTags=smoke,sanity - Run smoke + sanity
#runTags=all - Run all tests
timeout=10
browserName=chrome
screenshotsFolder=screenshots
test_type=fe